import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { PlaylistCreateRequest } from '@/types/music';

interface PlaylistCreationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (request: PlaylistCreateRequest) => void;
  isLoading: boolean;
}

const PlaylistCreationModal = ({
  isOpen,
  onClose,
  onSubmit,
  isLoading
}: PlaylistCreationModalProps) => {
  const [formData, setFormData] = useState<PlaylistCreateRequest>({
    name: '',
    description: '',
    public: false,
    collaborative: false,
    tracks: []
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
  };

  const resetForm = () => {
    setFormData({
      name: '',
      description: '',
      public: false,
      collaborative: false,
      tracks: []
    });
  };

  const handleClose = () => {
    resetForm();
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="bg-almond-white">
        <DialogHeader>
          <DialogTitle className="font-fira-code">Create a Playlist With These Recs<br/>(Find It In Your Account:) )</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="playlist-name " className="font-fira-code">Give a Name To Your Playlist</Label>
            <Input
              id="playlist-name"
              className="font-fira-code"
              placeholder="My Mood Playlist"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              required
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="playlist-description" className="font-fira-code"> Give a Description If You Want (Optional)</Label>
            <Textarea
              id="playlist-description"
              className="font-fira-code"
              placeholder="Generated by Chro.mA"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              rows={3}
            />
          </div>
          
          <div className="flex items-center space-x-2">
            <Switch
              className="font-fira-code"
              id="public-playlist"
              checked={formData.public}
              onCheckedChange={(checked) => setFormData({ ...formData, public: checked })}
            />
            <Label htmlFor="public-playlist" className="font-fira-code">Make playlist public</Label>
          </div>
          
          <div className="flex items-center space-x-2">
            <Switch
              className="font-fira-code"
              id="collaborative-playlist"
              checked={formData.collaborative}
              onCheckedChange={(checked) => setFormData({ ...formData, collaborative: checked })}
            />
            <Label htmlFor="collaborative-playlist" className="font-fira-code">Allow others to edit</Label>
          </div>
          
          <div className="flex gap-2 pt-4">
            <Button type="button" variant="outline" onClick={handleClose} className="font-fira-code">
              Cancel
            </Button>
            <Button type="submit" disabled={isLoading || !formData.name.trim()} className="font-fira-code">
              {isLoading ? 'Creating...' : 'Create Playlist'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default PlaylistCreationModal;
